export const priorities = [
  {slug:'economy',image:'/images/economy.jpg',kicker:'WORK, TAX AND ENTERPRISE',title:'More room to get ahead',headline:'Let effort pay again.',short:'Lower the tax on work, back small business and put competition before political control.',detail:'Raise the tax-free threshold, simplify business taxes and introduce a one-in, two-out rule for costly new regulation. Independent regulators, not ministers, will protect fair prices and open markets.',commitments:['Raise the personal tax-free threshold and index it to wages','Create one simple quarterly return for small firms and sole traders','Require every new regulation to publish its cost to households and business','Open government purchasing to young firms and regional suppliers','Protect independent competition enforcement in concentrated markets']},
  {slug:'security',image:'/images/security.jpg',kicker:'JUSTICE, POLICING AND DEFENCE',title:'Safe streets, secure nation',headline:'Order without overreach.',short:'Visible policing at home and dependable allies across the Columbian community.',detail:'Put more officers where people see them, target organised crime and cyber threats, and give courts the capacity to move cases quickly. Abroad, we will remain a reliable Columbian ally and invest in modern defence.',commitments:['Put neighbourhood teams on visible, multi-year staffing plans','Create specialist national units for organised crime, fraud and cyber threats','Fund additional court capacity and digital case management','Guarantee independent review of emergency and surveillance powers','Publish a ten-year defence capability and procurement plan']},
  {slug:'build',image:'/images/build.jpg',kicker:'HOUSING, TRANSPORT AND WATER',title:'Build what we need',headline:'From delay to delivery.',short:'Faster homes, better transport and reliable energy, without years lost to paperwork.',detail:'Create a single approvals pathway for nationally significant projects, unlock housing near transport, and invite competitive investment into rail, ports, water and clean firm power.',commitments:['Set binding decision deadlines for major planning applications','Allow more homes around rapid transit and established town centres','Create regional infrastructure agreements with transparent milestones','Use competitive delivery contracts for rail, ports and water renewal','Publish a national pipeline so builders can invest in people and equipment']},
  {slug:'services',image:'/images/services.jpg',kicker:'HEALTH, EDUCATION AND SKILLS',title:'Services that deliver',headline:'A guarantee of outcomes.',short:'Judge public services by the result for you, not the size of the department.',detail:'Guarantee timely primary care, publish school and hospital outcomes, expand technical pathways and let public, community and independent providers compete to deliver quality care.',commitments:['Introduce a primary-care access guarantee with regional reporting','Publish comparable waiting-time and treatment-outcome dashboards','Protect core literacy and numeracy time in every primary school','Build employer-designed technical academies in all major regions','Fund services around the citizen, whether delivery is public or independent']},
  {slug:'energy',image:'/images/energy.jpg',kicker:'ENERGY AND THE ENVIRONMENT',title:'Clean, firm, affordable power',headline:'Abundance is climate policy.',short:'Build a resilient electricity system that cuts emissions without rationing growth.',detail:'Replace stop-start intervention with a technology-neutral clean power market. Speed up grids, storage and generation while protecting landscapes through clear national standards.',commitments:['Create a single national connection process for new generation','Run long-term auctions for clean, firm capacity and storage','Modernise the grid before congestion becomes a growth tax','Price pollution consistently and return proceeds through lower taxes','Pay host communities a share of major energy-project revenues']},
  {slug:'regions',image:'/images/farm.jpg',kicker:'FARMS, ISLANDS AND REGIONS',title:'Power closer to home',headline:'One country, many strengths.',short:'Give regions the tools and revenue to shape their own growth.',detail:'Move practical decisions closer to communities, secure clean rural water and connect producers, islands and smaller cities to national and Columbian markets.',commitments:['Give regions multi-year transport and skills budgets','Create a clean-water renewal fund with public quality reporting','Upgrade farm-to-port freight corridors and cold-chain capacity','Give Myrati greater authority over tourism and local transport','Share royalties from nationally significant projects with host regions']},
  {slug:'government',image:'/images/digital.jpg',kicker:'DEMOCRACY AND GOVERNMENT',title:'A state worthy of trust',headline:'Open by default.',short:'Protect constitutional government and make the public sector radically easier to see and use.',detail:'Rights, checks and honest administration are not obstacles to action. They are how lasting reform earns consent. LCA will pair a capable state with real limits on political power.',commitments:['Publish contracts, performance data and ministerial meetings by default','Create one secure digital front door for national services','Require sunset votes for emergency powers','Strengthen independent fiscal and electoral institutions','Give citizens a right to a timely decision from public agencies']},
  {slug:'world',image:'/images/port.jpg',kicker:'TRADE AND COLUMBIA',title:'Confident in the world',headline:'Open, allied, prepared.',short:'Use Caprica’s commercial strength and Columbian ties to keep the country secure and prosperous.',detail:'Caprica should be a dependable Columbian ally, a champion of open trade and a practical partner across the Aortic Sea. Economic security and national security will be planned together.',commitments:['Deepen the Columbian single market in services and digital trade','Create secure supply agreements for medicines, energy and critical technology','Expand port capacity and trusted-trader lanes','Coordinate cyber defence with Columbian partners','Tie development partnerships to transparent, measurable outcomes']}
];

export const candidates = [
  {slug:'alan',name:'Alan Bluespan III',first:'Alan',region:'VICE PRESIDENT',seat:'National ticket',image:'/images/alan.png',quote:'“The citizen, not the system, should be the protagonist.”',bio:'An economist and entrepreneur from Chasmia, Alan brings a reformer’s discipline and a builder’s optimism to the national ticket. His 2064 campaign is centred on constitutional government, economic renewal and restoring confidence that public institutions work for citizens.',focus:['Constitutional government','A more competitive economy','Caprica’s place in Columbia']},
  {slug:'alistair',name:'Alistair Foulke-McKeon',first:'Alistair',region:'AMBROSIA',seat:'Candidate for MP',image:'/images/alistair.png',quote:'“Ambrosia should never have to choose between its way of life and a prosperous future.”',bio:'Alistair’s plan backs family farms, clean water and the young people who want to make their future in Ambrosia. He is campaigning for reliable freight links, practical apprenticeships and rural services that respect the distance between communities.',focus:['Farm export corridors','Clean rural water','Regional apprenticeships']},
  {slug:'patrick',name:'Patrick Cutter',first:'Patrick',region:'CHASMIA',seat:'Candidate for MP',image:'/images/patrick.png',quote:'“Chasmia built Caprica. Now we will build its next generation of industry.”',bio:'A former Prime Minister and experienced business leader, Patrick is focused on advanced manufacturing, shipbuilding and skilled work. He wants Chasmia’s research institutions, energy producers and industrial firms working from one long-term regional growth plan.',focus:['Advanced manufacturing','Research partnerships','Energy security']},
  {slug:'stoner',name:'JB Stoner',first:'JB',region:'MYRATI',seat:'Candidate for MP',image:'/images/stoner.png',quote:'“Prosperity must travel beyond the waterfront, and power must travel back to Myrati.”',bio:'JB is campaigning for local autonomy, better connections and a tourism economy whose success reaches every community. His programme would keep more visitor revenue on the islands while improving transport, skills and opportunities beyond Port Aaron.',focus:['Island transport','Local decision-making','Skills and tourism']},
  {slug:'cardoso',name:'Fernando Henrique Cardoso',first:'Fernando',region:'OPLANA',seat:'Candidate for MP',image:'/images/cardoso.png',quote:'“Steady reform can deliver lasting progress.”',bio:'Fernando offers experience, calm judgment and a practical agenda for Oplana’s families, coast and growing businesses. His priorities combine coastal resilience with faster primary care, simpler rules for local firms and responsible investment in Langston’s future.',focus:['Coastal resilience','Small business','Better primary care']},
  {slug:'libero',name:'Roberto Libero',first:'Roberto',region:'RENO',seat:'Candidate for MP',image:'/images/libero.jpg',quote:'“Keep Reno moving, keep it safe, and keep opportunity within reach.”',bio:'Roberto champions the entrepreneurs, commuters and families who make Reno one of Caprica’s most dynamic communities. He is focused on safer neighbourhoods, better links to Montiablo and more housing choices close to jobs, schools and everyday services.',focus:['Faster commutes','Safer neighbourhoods','Housing choice']},
  {slug:'ronan',name:'Ronan Hayward',first:'Ronan',region:'MONTIABLO',seat:'Candidate for MP',image:'/images/ronan.png',quote:'“A great capital opens doors, it does not put up barriers.”',bio:'An experienced reformer and former Mayor-Governor, Ronan Hayward brings a record of liberal reform and a clear plan for the capital to the LCA team. He is campaigning for homes around transit, open digital government and a city economy that remains active, safe and welcoming after dark.',focus:['Homes near transit','Open, digital government','A thriving night-time economy']},
  {slug:'pepe',name:'Pepe Marti Rutte',first:'Pepe',region:'CAMBRIA',seat:'Candidate for MP',image:'/images/pepe.png',quote:'“Cambria should be a place where a good idea can become a good living.”',bio:'Pepe is standing for a more enterprising, connected and affordable Cambria. His campaign is focused on opening doors for young workers and local firms, expanding practical training, and making it easier to build homes near jobs and transport. He wants national government to give Cambrian communities the tools to grow on their own strengths.',focus:['Skills for young workers','Backing local enterprise','Homes near transport']},
  {slug:'pagi',name:'Rupert Pagi Shaw',first:'Rupert',region:'KALAHOOSKA',seat:'Candidate for MP',image:'/images/pagi.png',quote:'“Kalahooska deserves a strong voice in the room where national decisions are made.”',bio:'Rupert is campaigning to connect Kalahooska’s communities to opportunity without losing the character that makes the region distinct. His priorities are dependable transport, resilient local services and a practical settlement that gives regional leaders more authority over the decisions closest to home.',focus:['Regional transport','Resilient local services','Decisions closer to home']},
  {slug:'mathieu',name:'Mathieu Jeon',first:'Mathieu',region:'PLEUCADEUC',seat:'Candidate for MP',image:'/images/mathieu.jpg',quote:'“A new generation should be able to build its future in Pleucadeuc.”',bio:'Mathieu brings a generational perspective to the LCA team and a focused programme for Pleucadeuc. He is campaigning for attainable housing, modern technical education and faster digital connections, so young people and growing firms can choose the region with confidence.',focus:['Attainable housing','Technical education','Digital connectivity']}
];

export const events=[
  {slug:'caprica-we-can-build',day:'28',month:'AUG',time:'18:30',type:'ALLIANCE FORUM',title:'The Caprica We Can Build',place:'Civic Hall · Montiablo',description:'Alan Bluespan III and LCA candidates take unscripted questions on the alliance, housing, transport and the constitutional limits of government.'},
  {slug:'ambrosia-roundtable',day:'04',month:'SEP',time:'10:00',type:'REGIONAL VISIT',title:'Ambrosia Farm & Water Roundtable',place:'Meridian Cooperative · Ambrosia',description:'A working session with growers, exporters and rural families on clean water, freight links and keeping the next generation in Ambrosia.'},
  {slug:'chasmia-future',day:'12',month:'SEP',time:'19:00',type:'TOWN HALL',title:'Industry, Skills and Chasmia’s Future',place:'Littlewoods Exchange · Chasmia',description:'Patrick Cutter hosts manufacturers, apprentices and researchers for a practical conversation about Chasmia’s next industrial chapter.'}
];
